// Syrup auto-generated file

export type { CollectionInput } from "./CollectionInput"
export type { CollectionPublicationInput } from "./CollectionPublicationInput"
export type { CollectionRuleInput } from "./CollectionRuleInput"
export type { CollectionRuleSetInput } from "./CollectionRuleSetInput"
export type { CustomerInput } from "./CustomerInput"
export type { ImageInput } from "./ImageInput"
export type { InventoryItemInput } from "./InventoryItemInput"
export type { InventoryLevelInput } from "./InventoryLevelInput"
export type { MailingAddressInput } from "./MailingAddressInput"
export type { MetafieldInput } from "./MetafieldInput"
export type { PrivateMetafieldInput } from "./PrivateMetafieldInput"
export type { PrivateMetafieldValueInput } from "./PrivateMetafieldValueInput"
export type { ProductVariantInput } from "./ProductVariantInput"
export type { SEOInput } from "./SEOInput"
